### ISSUE TITLE
Exception on findLabel

### ISSUE THREAD

**Issue by mwinters-stuff** [expandjs/xp-input-behavior#3]
This line 

```
  return found || XP.findParentElement(self, 'label') || null;
```

in the findParentElement will throw an exception when it cant find label.. Used in a mat-text-field.

```
    <mat-dialog id="dialog" label="{{_dialogTitle(_node.id)}}" auto-hide-disabled>
      <!-- <form> -->
        <table>
          <tr>
            <td colspan="2">
              <mat-text-field id="editlocation" value="" model="{{_node.location}}" label="Location" description="Where this node is" floating-label required focused inline></mat-text-field>
            </td>
          </tr>
          <tr>
            <td colspan="2">
              <mat-text-field id="editnumber" value="{{_node.number}}" label="RF24 Net Number" description="RF24 Network Node Number" type="number" floating-label required></mat-text-field>
            </td>
          </tr>
          <tr>
            <td colspan="2">
              <mat-text-field value="{{_node.details}}" label="Details" description="Extra Details" floating-label required></mat-text-field>
            </td>
          </tr>
          <tr>
            <td>
              <mat-checkbox checked="{{_node.insideNode}}" label="Inside Node" description="Reports as inside temperature and humidity"></mat-checkbox>
            </td>
            <td>
              <mat-checkbox checked="{{_node.outsideNode}}" label="Outside Node" description="Reports as outside weather"></mat-checkbox>
            </td>
          </tr>
          <tr>
            <td>
              <mat-checkbox checked="{{_node.calcDewPoint}}" label="Calculate Dew Point" description="Calculate dew point from temperature and humidity"></mat-checkbox>
            </td>
            <td>
              <mat-checkbox checked="{{_node.offline}}" label="Offline" description="Node is offline and not reporting"></mat-checkbox>
            </td>
          </tr>
        </table>
      <!-- </form> -->

      <mat-button label="Cancel" class="action" on-xp-activate="_dialogCancel"></mat-button>
      <mat-button label="OK" class="action" on-xp-activate="_dialogOk"></mat-button>
    </mat-dialog>
```

The call stack is

```
Uncaught TypeError: Cannot read property 'call' of undefinedexp.matches.matches @ index.js:1830
exp.findParentElement.findParentElement @ index.js:878
Polymer.XPInputBehaviorImp.attached @ xp-input-behavior.html:880
Polymer.Base._addFeature._invokeBehavior @ polymer-micro.html:392
Polymer.Base._addFeature._doBehavior @ polymer-micro.html:385
(anonymous function) @ polymer-micro.html:196
```

I cant figure this out - for my project it is happening on all that use the behavour.

**Comment by Pupix** [comment]
Hello!

Just tried the example above and I do not get the said problem. What browser are you using?

Sometimes bower's cache can cause problem. You should try clean it using `bower cache clean` and reinstall everything with `bower install` to see if it fixes anything.

Cheers.

**Comment by mwinters-stuff** [comment]
Chrome latest, 64 bit on Linux. Did the cache clean and install after removing bower_components, no difference..
I had this error once before and with a number of added log messages in the expandjs I managed to figure out what was wrong, I cant figure it this time - What is needed is more information in the error messages! eg, what component and what call its looking for..

**Comment by mwinters-stuff** [comment]
Looks like it was my problem, went through a process of elimination right down to index, What it was is the element that owned the inputs had a property called "node" renaming this property seems to have solved it - odd though that the elements showing an error were not the actual one causing it.. The 0.9.x versions of expandjs didnt show an error with this property..
Closing Issue..

**Comment by Pupix** [comment]
Most of 0.9.x DOM methods used directly the HTML elements, however those would break when used inside ShadowDOM. Now whenever possible they use HTML nodes allowing for the `shadow-root` to be used when trying to query inside ShadowDOM and HTML elements when trying to query the LightDOM.
